//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public string cedula { get; set; }
        public string numero { get; set; }
        public string tipo { get; set; }
    }
}
